<a href="https://colab.research.google.com/github/jackqk/pandas-note/blob/master/Numpy_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

In [0]:
import numpy as np
np.version.version

'1.17.3'

## 常用属性
shape<br>
dtype<br>

# 一、Create Numpy Arrays

## list直接转换

In [0]:
mylist=[1,2,3]
x = np.array(mylist)
x

array([1, 2, 3])

In [0]:
y = np.array([4,5,6])
y

array([4, 5, 6])

In [0]:
m = np.array([[7,8,9],[10,11,12]])
m

array([[ 7,  8,  9],
       [10, 11, 12]])

In [0]:
#查看numpy 形状
m.shape

(2, 3)

## arange创建

In [0]:
n = np.arange(13)
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [0]:
# 起始为止，终止为止，步长（其实就是等差数列，指定差值）
n = np.arange(0, 30, 2)
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [0]:
#形状修改，修改完赋值回去
n = n.reshape(3, 5)
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

## linspace创建


In [0]:
# 起始为止，终止为止，步长（其实就是等差数列，指定个数）
o = np.linspace(0, 4, 9)
o

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [0]:
#形状修改，修改完不用赋值（这里需要知道与reshape之间的区别）
o.resize(3,3)
o

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

## numpy几个内置函数

In [0]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [0]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [0]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [0]:
np.diag([1.,5,3.2,7,8])

array([[1. , 0. , 0. , 0. , 0. ],
       [0. , 5. , 0. , 0. , 0. ],
       [0. , 0. , 3.2, 0. , 0. ],
       [0. , 0. , 0. , 7. , 0. ],
       [0. , 0. , 0. , 0. , 8. ]])

## 组合创建

In [0]:
np.array([1,2,3]*3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [0]:
#注意与上面例子的区别
np.repeat([1,2,3], 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [0]:
p = np.ones([2,3], int)
p

array([[1, 1, 1],
       [1, 1, 1]])

In [0]:
#垂直堆叠
np.vstack([p, 2*p])

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

In [0]:
#水平堆叠
np.hstack([p, 2*p])

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

# 二、Operation

### 普通四则运算

In [0]:
x = np.array([1,2,3])
y = np.array([4,5,6])
x + y

array([5, 7, 9])

In [0]:
x * y

array([ 4, 10, 18])

In [0]:
x ** 2

array([1, 4, 9])

### 线性代数运算

In [0]:
#线性代数相乘
yy = np.vstack([y,y])
display(x)
display(yy.T)
x.dot(yy.T)

array([1, 2, 3])

array([[4, 4],
       [5, 5],
       [6, 6]])

array([32, 32])

In [0]:
z = np.array([y, 2*y])
z

array([[ 4,  5,  6],
       [ 8, 10, 12]])

In [0]:
z.shape

(2, 3)

In [0]:
z.T

array([[ 4,  8],
       [ 5, 10],
       [ 6, 12]])

In [0]:
z.T.shape

(3, 2)

In [0]:
z.dtype

dtype('int64')

In [0]:
z = z.astype('f')
z.dtype

dtype('float32')

### 数学运算

In [0]:
a = np.array([-4, -2, 1, 3, 5])
a

array([-4, -2,  1,  3,  5])

In [0]:
a.sum()

3

In [0]:
a.max()

5

In [0]:
a.min()

-4

In [0]:
a.mean()

0.6

In [0]:
a.std()

3.2619012860600183

In [0]:
a.argmax()

4

In [0]:
a.argmin()

0

# 三、Index / Slicing

## 一维

In [0]:
s = np.arange(13) ** 2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

In [0]:
s[0], s[4]

(0, 16)

In [0]:
#s[a:b] ==> 结尾 = b - 1；个数 = b - a； 
s[0:3]

array([0, 1, 4])

In [0]:
s[1:5]

array([ 1,  4,  9, 16])

In [0]:
s[-4:]

array([ 81, 100, 121, 144])

In [0]:
#往前遍历
s[-5::-2]

array([64, 36, 16,  4,  0])

## 二维

In [0]:
r = np.arange(36)
r.resize([6,6])
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [0]:
r[2,2]

14

In [0]:
r[3, 3:6]

array([21, 22, 23])

In [0]:
r[:2, -1]

array([ 5, 11])

In [0]:
r[-1, ::2]

array([30, 32, 34])

## 赋值

In [0]:
r[r>30]

array([31, 32, 33, 34, 35])

In [0]:
r[r>30]=30
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [0]:
r2 = r[:3, :3]
r2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

In [0]:
#修改会影响原始r
r2[:] = 0
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [0]:
r

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [0]:
#调用copy就不会影响原始数据r了
r_copy = r.copy()
r_copy

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [0]:
r_copy[:]=10
print(r)
print()
print(r_copy)

[[ 0  0  0  3  4  5]
 [ 0  0  0  9 10 11]
 [ 0  0  0 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 30 30 30 30 30]]

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]


# 四、遍历

In [0]:
test = np.random.randint(0, 10, (4, 3))
test

array([[4, 4, 6],
       [2, 7, 4],
       [1, 0, 6],
       [6, 4, 6]])

In [0]:
#方法一：按行遍历
for row in test:
  print(row)

[4 4 6]
[2 7 4]
[1 0 6]
[6 4 6]


In [0]:
#方法二：按行遍历：使用len(test)返回行数
for i in range(len(test)):
  print(test[i])

[4 4 6]
[2 7 4]
[1 0 6]
[6 4 6]


In [0]:
#方法三：enumerate
for i, row in enumerate(test):
    print('row', i, 'is ', row)

row 0 is  [4 4 6]
row 1 is  [2 7 4]
row 2 is  [1 0 6]
row 3 is  [6 4 6]


In [0]:
test2 = test ** 2
test2

array([[16, 16, 36],
       [ 4, 49, 16],
       [ 1,  0, 36],
       [36, 16, 36]])

In [0]:
#同时遍历
for i, j in zip(test, test2):
  print(i,'+', j,'=', i+j)

[4 4 6] + [16 16 36] = [20 20 42]
[2 7 4] + [ 4 49 16] = [ 6 56 20]
[1 0 6] + [ 1  0 36] = [ 2  0 42]
[6 4 6] + [36 16 36] = [42 20 42]
